Repository TheGymRwanda/unit8-maroon, pull requests merged in 2022-12, with the labels that each got.

#21 Feat: about big screen
  components/functions/OneBlock.js
  components/functions/OneTab.jsx
  components/section/About.jsx
  components/section/AboutSection/About.jsx
  components/section/AboutSection/AboutMobile.jsx
  components/ui/Button.jsx
  package-lock.json
  package.json
  pages/about.js
  pages/index.js
  public/assets/icons/down-arrow.png
  public/assets/icons/left-arrow.png
  public/assets/icons/link-arrow.png
  public/assets/icons/right-arrow.png
  public/assets/icons/up-arrow.png
  public/assets/images/bitlipa.png
  public/assets/images/dacade.png
  public/assets/images/even.png
  public/assets/images/lab3.png
  public/assets/images/neueux.png
  public/assets/images/symplifi.png
  public/assets/images/team.png
  public/assets/images/utu.png
  tailwind.config.js
Labels: ready for review

#25 fix: Fixing gaps in project and adding about in index
  components/section/Project.jsx
  pages/index.js
  tailwind.config.js
Labels: ready for review

#7 Feat: about us mobile
  components/functions/OneBlock.js
  components/section/AboutSection/About.jsx
  components/section/AboutSection/AboutMobile.jsx
  components/ui/AboutTab.jsx
  components/ui/DownArrow.jsx
  pages/about.js
  pages/index.js
  public/assets/icons/arrow-down.svg
  tailwind.config.js
Labels: ready for review

#23 Fix: Fixed footer paddings
  components/layout/Footer.jsx
  components/section/Expertise.jsx
  pages/index.js
  tailwind.config.js
Labels: ready for review

#14 Feat: blog component
  components/cards/BlogCard.jsx
  components/section/Blog.jsx
  components/section/Footer.jsx
  components/ui/Tag.jsx
  pages/index.js
  tailwind.config.js
Labels: in-progress

#34 feat: Adding a purple selecting background
  styles/globals.css
Labels: Ready to be merged

#32 Fix: fixing bugs on expertise section
  components/section/Expertise.jsx
  dataCollection/data.js
  package-lock.json
  package.json
Labels: Ready to be merged

#37 Fixing the hovering on the heading of About Section
  components/functions/OneTab.jsx
Labels: To be approved

#33 Fix: Project section
  components/cards/ProjectCard.jsx
  components/section/Project.jsx
  components/section/Project/Project.jsx
  components/section/Project/ProjectMob.jsx
  components/ui/Link.jsx
  pages/index.js
Labels: ready for review
